### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by greenhat616** [Watfaq/clash-rs#151]
I wonder what block this support listed in Roadmap. Thx

**Comment by ibigbug** [comment]
it's not impossible, however some dependency build issues need to be addressed.

see https://github.com/Watfaq/clash-rs/pull/152

**Comment by ibigbug** [comment]
you can give it a try if you want https://github.com/Watfaq/clash-rs/releases/tag/v0.1.7

**Comment by greenhat616** [comment]
I will have a try in recent few days. Thx

**Comment by greenhat616** [comment]
I tested ss config in windows.

I face two issues, which is blocked normal use:
* `plugin_opts` should be `plugin-opts`, which is not compatible with `clash` or `clash-meta`
* `simple-obfs is deprecated, please use v2ray-plugin instead` error was thrown and connection was closed.
![image](https://github.com/Watfaq/clash-rs/assets/41122242/971e1ad8-8241-4a9f-845e-2caef9d69bce)

I don't known whether it is platform-spec issue.
