### ISSUE TITLE
armv8 not supported

### ISSUE THREAD

**Issue by Nelocompne** [Watfaq/clash-rs#180]
BoringSSL supports `arm64 android`, but doesn't seem to support `arm v8` for general purpose machines, which also means that `clash-rs` can't compile programs for `arm v8` for general purpose machines because` clash-rs` uses BoringSSL, is that right?

**Comment by ibigbug** [comment]
Hey thanks for looking into this.

you are probably right however there seems to be certain level of support discussed in this post, not sure if that helps. https://www.amongbytes.com/post/201804-comparing-mbedtls-to-boringssl/

while I'm not an expert of this, what would be the main devices that run on `arm v8` ? if that's so widely used I'm happy to consider other SSL implementations that supports more plats

**Comment by Nelocompne** [comment]
Actually, I have a [FriendlyELEC](https://friendlyelec.com/)'s CPU board, such as [NanoPi R2S](https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R2S), where you can see its CPU and other [related parameters](https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R2S#Hardware_Spec). I want use clash-rs on it.

I usually apply it on OpenWrt, which are now common on many ARM CPU machines equipped with them. If you are willing to provide support, it would be appreciated!

**Comment by ibigbug** [comment]
i think i managed to build it on arm https://github.com/Watfaq/clash-rs/releases/tag/v0.1.8 if you want to try it out

**Comment by Nelocompne** [comment]
I try [v0.1.8](https://github.com/Watfaq/clash-rs/releases/tag/v0.1.8)

cannot run

on OpenWrt 23.05.0-rc3 armv8
```shell
root@OpenWrt:~# ./clash-armv7-unknown-linux-gnueabihf
./clash-armv7-unknown-linux-gnueabihf: line 1: syntax error: unexpected word (expecting ")")
root@OpenWrt:~# ./clash-armv7-unknown-linux-gnueabi
./clash-armv7-unknown-linux-gnueabi: line 1: syntax error: unexpected word (expecting ")")
root@OpenWrt:~# ./clash-aarch64-unknown-linux-gnu
-ash: ./clash-aarch64-unknown-linux-gnu: not found
```

on Armbian (22.08.0-trunk) aarch64
```shell
root@armbian:~# ./clash-aarch64-unknown-linux-gnu
./clash-aarch64-unknown-linux-gnu: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./clash-aarch64-unknown-linux-gnu)
./clash-aarch64-unknown-linux-gnu: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./clash-aarch64-unknown-linux-gnu)
./clash-aarch64-unknown-linux-gnu: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./clash-aarch64-unknown-linux-gnu)
root@armbian:~# ./clash-armv7-unknown-linux-gnueabi
-bash: ./clash-armv7-unknown-linux-gnueabi: No such file or directory
root@armbian:~# ./clash-armv7-unknown-linux-gnueabihf
-bash: ./clash-armv7-unknown-linux-gnueabihf: No such file or directory
```

**Comment by ibigbug** [comment]
Alright. I think that's back to this https://github.com/Watfaq/clash-rs/issues/90

The build is off a much newer glibc on the GitHub actions image Ubuntu 22. 

Need to figure it out to support older versions.

**Comment by ibigbug** [comment]
root@OpenWrt:~# ./clash-aarch64-unknown-linux-gnu
-ash: ./clash-aarch64-unknown-linux-gnu: not found

This one does look like the file was not downloaded or something though.

**Comment by greenhat616** [comment]
> root@OpenWrt:~# ./clash-aarch64-unknown-linux-gnu -ash: ./clash-aarch64-unknown-linux-gnu: not found
> 
> This one does look like the file was not downloaded or something though.

It might be a musl built system issue, ref: https://stackoverflow.com/questions/66963068/docker-alpine-executable-binary-not-found-even-if-in-path

in most of case, OpenWRTis built with `musl` .

```
# ldd
musl libc (x86_64)
Version 1.2.4
Dynamic Program Loader
Usage: ldd [options] [--] pathname
```

**Comment by greenhat616** [comment]
I tested it in AWS ARM64 Server, the `arm8`, aka `aarch64`, is work as expected.

![image](https://github.com/Watfaq/clash-rs/assets/41122242/60a37fcf-2517-4ce0-947b-a530ee55bcb7)
![image](https://github.com/Watfaq/clash-rs/assets/41122242/54d3a713-1d14-414d-9f5a-5d3fae73b35d)

**Comment by Nelocompne** [comment]
> @Nelocompne This is a dev build via `RUSTFLAGS='-C target-feature=+crt-static' ./scripts/build.sh aarch64-unknown-linux-gnu`. [clash-aarch64-unknown-linux-gnu.zip](https://github.com/Watfaq/clash-rs/files/13458022/clash-aarch64-unknown-linux-gnu.zip) ![image](https://private-user-images.githubusercontent.com/41122242/285431677-641ab34f-efb1-4750-aad6-ac0d7159b4a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NTYwNzUsIm5iZiI6MTcwMDg1NTc3NSwicGF0aCI6Ii80MTEyMjI0Mi8yODU0MzE2NzctNjQxYWIzNGYtZWZiMS00NzUwLWFhZDYtYWMwZDcxNTliNGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI0VDE5NTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhODAwMzI3ZTMyZGFmYWRkNWU1M2NiZTQ0NGVlNTE4ZDQzZTBlMDA3OWRmYjFiZjFkZGZjOGQ5MTA2N2M5MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ylUsZYou2ZCxJQdgNWXD26zoMkP0v0hzB_-lrlUDzg)
> 
> Please have a try to test whether it can run in your platfrom. thx

thank you build, it work on my `openwrt` :
```shell
root@OpenWrt:~/greenhat616# ./clash-aarch64-unknown-linux-gnu -h
Usage: clash-aarch64-unknown-linux-gnu [OPTIONS]

Options:
  -d, --directory <DIRECTORY>
  -c, --config <FILE>          [default: config.yaml]
  -h, --help                   Print help
  -V, --version                Print version
root@OpenWrt:~/greenhat616# ./clash-aarch64-unknown-linux-gnu -V
clash 0.1.8
root@OpenWrt:~/greenhat616# ./clash-aarch64-unknown-linux-gnu
  2023-11-24T20:14:32.269247Z  INFO clash_lib::app::inbound::network_listener: HTTP TCP listening at: 0.0.0.0:8888
    at clash_lib/src/app/inbound/network_listener.rs:118

  2023-11-24T20:14:32.269400Z  INFO clash_lib: receive shutdown signal
    at clash_lib/src/lib.rs:269

```

```shell
root@OpenWrt:~/greenhat616# curl -x 127.0.0.1:8888 https://www.bilibili.com -I
HTTP/1.1 200 OK
date: Fri, 24 Nov 2023 20:17:18 GMT

HTTP/2 200
date: Fri, 24 Nov 2023 20:17:19 GMT
content-type: text/html; charset=utf-8
support: nantianmen
vary: Origin,Accept-Encoding
expires: Fri, 24 Nov 2023 20:17:18 GMT
cache-control: no-cache
x-cache-webcdn: MISS from blzone02
x-cache-time: 0
x-save-date: Fri, 24 Nov 2023 20:17:19 GMT

```

i think we have found the good to build.

**Comment by ibigbug** [comment]
the static build has been attached to releases https://github.com/Watfaq/clash-rs/releases/tag/v0.1.9

**Comment by Nelocompne** [comment]
new releases v0.1.9 `static-crt` can work on my `openwrt`.
so arm8 is already supported i will close this issue.
