### ISSUE TITLE
fix: use with `shadowsocks` transport 

### ISSUE THREAD

**Issue by greenhat616** [Watfaq/clash-rs#188]
As https://github.com/Watfaq/clash-rs/issues/151#issuecomment-1822713884 illustrated,
* [x] should do a alias `plugin-opts` for `plugin_opts` to compatible with `clash` and `clash-meta`
* [x] revert `simple-obfs` plugin and just print a warning `deprecated` until `v2ray-plugin` get implemented and widely used.
  * [x] impl `tls simple-obfs`, like https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/transport/simple-obfs/tls.go

**Comment by ibigbug** [comment]
thank you!

well i didn't have a change to setup obfs on ss so that part is lack of test tbh

**Comment by greenhat616** [comment]
> thank you!
> 
> well i didn't have a change to setup obfs on ss so that part is lack of test tbh

Yeah. the impl is not work due to wrong request header and response offset, and i fix it now.
