### ISSUE TITLE
Incorrect match order

### ISSUE THREAD

**Issue by greenhat616** [Watfaq/clash-rs#204]
The correct match should be "🤖 ChatGPT"
![image](https://github.com/Watfaq/clash-rs/assets/41122242/63a367d5-fb06-4d13-8ad0-334f270164af)

Currect match rule is "Match", which is not correspond with other core does
![image](https://github.com/Watfaq/clash-rs/assets/41122242/20a6fe9b-9e04-4dfb-bb3d-eda07ff27534)

Let me have a check later, when I finish this pr https://github.com/keiko233/clash-nyanpasu/pull/47

**Comment by ibigbug** [comment]
https://github.com/Watfaq/clash-rs/issues/602

**Comment by ibigbug** [comment]
It looks we need to separate put an extra filed on the Session to save the original domain https://github.com/Watfaq/clash-rs/blob/master/clash_lib/src/app/router/mod.rs#L92
