### ISSUE TITLE
Windows arm64 build requirements

### ISSUE THREAD

**Issue by greenhat616** [Watfaq/clash-rs#210]
It was blocked by `ring` 0.16, and get supported in `ring` 0.17:

These deps are using `ring` 0.16:
* boringtun - `master` branch has got merged v0.17 support
* hickory-client - `master` branch has got merged v0.17 support
  * but it still is **blocked** by `rustls` v0.21 due to `sct` v0.7.0, which is required `ring` v0.16

Other requirements haven't test yet - due to blocked by ring.

**Comment by ibigbug** [comment]
https://github.com/shadowsocks/shadowsocks-rust/pull/1379

https://github.com/hickory-dns/hickory-dns/pull/2107
