### ISSUE TITLE
closed with error crypto error: BAD_DECRYPT

### ISSUE THREAD

**Issue by xmh0511** [Watfaq/clash-rs#216]
```
grpc initialization error
closed with error crypto error: BAD_DECRYPT
 error: invalid peer certificate: Other(UnsupportedCertVersion)
```

**Comment by ibigbug** [comment]
UnsupportedCertVersion

Likely to be https://github.com/rustls/webpki/issues/29#issuecomment-1453783741

**Comment by xmh0511** [comment]
`clash-rs` should support this certification, the core clash written by Golang supports this configuration and can work well.

**Comment by xmh0511** [comment]
https://github.com/keiko233/clash-nyanpasu/issues/54

**Comment by ibigbug** [comment]
I don't know how to reproduce this, if the issue is the cert, if you don't mind sharing a server that raises the error.

**Comment by xmh0511** [comment]
> I don't know how to reproduce this, if the issue is the cert, if you don't mind sharing a server that raises the error.

You can test it with https://github.com/keiko233/clash-nyanpasu, it has other clash cores, under the same server configuration files, the other core can work but `clash-rs` cannot.

I can supply you with this one server
`{ name: '香港 01 | 专线', type: vmess, server: hk01.84d4d2ae-211c-475f-9076-35fdd96d779b.940a60a7-6cb5-4fa7-bd73-23230d77aa0e.yiyuanjichang.org, port: 443, uuid: 29c79018-29c3-4dd1-aa86-1364f4bd8330, alterId: 0, cipher: auto, udp: true, tls: true, skip-cert-verify: true, servername: www.12306.cn, network: grpc, grpc-opts: { grpc-service-name: '12306' } }`

**Comment by ibigbug** [comment]
Thanks. Will have a look later. I've saved the info, you can delete it if you want.

**Comment by xmh0511** [comment]
> Thanks. Will have a look later. I've saved the info, you can delete it if you want.

Ok. if you want the complete configuration file, I can send it to your email for security.

**Comment by ibigbug** [comment]
No that should be enough. Will let you know if I need more details.

**Comment by xmh0511** [comment]
@ibigbug I tested the latest version, It still doesn't work. The given node can have a timeout test however cannot open any website through the node. Moreover, some other nodes cannot have a timeout test.
![452590302](https://github.com/Watfaq/clash-rs/assets/17973891/fbdd9d1d-f084-4de0-b2ea-6c21971feb04)
<img width="833" alt="截屏2023-12-28 11 02 40" src="https://github.com/Watfaq/clash-rs/assets/17973891/fb88d0e3-4f85-4c7d-8288-b45e0c4091ee">

**Comment by ibigbug** [comment]
Could you send you config to dev@watfaw.com 

There might be other issues.

**Comment by xmh0511** [comment]
> Could you send you config to [dev@watfaw.com](mailto:dev@watfaw.com)
> 
> There might be other issues.

I have sent it to you, check it out.

**Comment by xmh0511** [comment]
@ibigbug The email responded me with the error:
```
 DNS Error: DNS type 'mx' lookup of watfaw.com responded with code NXDOMAIN Domain name not found: watfaw.com Learn more at https://support.google.com/mail/?p=BadRcptDomain 
```

**Comment by ibigbug** [comment]
Sorry. A dev@watfaq.com. I typed too fast.

**Comment by ibigbug** [comment]
i took one failed proxy `yiyuanjichang.com` and the original go clash can't use it either.

more over the grpc init is rejected by cloudflare with

```
grpc init stream resp: Response { status: 403, version: HTTP/2.0, headers: {"server": "cloudflare", "date": "Thu, 28 Dec 2023 08:32:54 GMT", "content-type": "text/html", "content-length": "151", "cf-ray": "83c874958f89a973-SYD"}, body: RecvStream { inner: FlowControl { inner: OpaqueStreamRef { stream_id: StreamId(1), ref_count: 2 } } } }
```

maybe consult your provider

**Comment by xmh0511** [comment]
@ibigbug 
>  original go clash can't use it either.

The `Clash Premium` written by Go can use it. 
<img width="800" alt="截屏2023-12-28 17 15 30" src="https://github.com/Watfaq/clash-rs/assets/17973891/2608424b-33c4-404b-8149-5b0e538daeb6">
<img width="800" alt="截屏2023-12-28 17 15 14" src="https://github.com/Watfaq/clash-rs/assets/17973891/9a4c997a-60ee-4f29-9f94-6292e70ed8d2">
