### ISSUE TITLE
The `clash-rs` in `clash-verge` cannot use the nodes that `clash-premium` can

### ISSUE THREAD

**Issue by xmh0511** [Watfaq/clash-rs#238]
Since https://github.com/Watfaq/clash-rs/issues/216 has been partially fixed for timeout test, however the traffic proxy cannot work when using `clash-rs` while `clash-premium` can work well. 

https://github.com/Watfaq/clash-rs/assets/17973891/0ae21413-d644-4007-8dc4-230ecb554e7e

Moreover, all these nodes that have the correct timeout can proxy traffic when using `clash-premium` but they all fail when using `clash-rs`.

**Comment by ibigbug** [comment]
Thanks for reporting this.

From my side I don't have any idea why it would fail the grpc handshake for certain proxy server, such a the one i tested which got 403 from cloudflare. 

I suspect there's something that needs to be handled differently, though I don't know what is it.
