### ISSUE TITLE
add integration tests

### ISSUE THREAD

**Issue by ibigbug** [Watfaq/clash-rs#246]

**Comment by VendettaReborn** [comment]
How about test with docker? Similar to the [docker test](https://github.com/MetaCubeX/mihomo/blob/meta-main/test/docker_test.go) in clash.meta

I've implemented one in my local environment, it works well, and i've found a bug in http2 transport (shall be fixed in another issue)

**Comment by ibigbug** [comment]
yes that's a good option. we also have some proxy server setups here https://github.com/Watfaq/clash-rs/tree/master/docker, which might be useful to run tests

**Comment by VendettaReborn** [comment]
yep, i see that. But that need developers' manual operations, right? I'd like to run/destroy the docker container in the unit test code, so the correctness can be verified with `cargo test` .

**Comment by ibigbug** [comment]
yeah it's definitely good to automate things as much as possible. however not sure whether they should be unit tests, maybe we should add separate integration tests https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html

**Comment by VendettaReborn** [comment]
I shall create a PR for this feature
