### ISSUE TITLE
clash-rs runs slowly on my Windows 10 PC

### ISSUE THREAD

**Issue by ericclose** [Watfaq/clash-rs#256]
Clash-RS runs slowly on my Windows 10 PC. It took almost 20 seconds to get it running and logging. And I don't see too much load when I look at the Performance section of the Task Manager.

I'm not sure if it's a system related issue or a hardware performance related issue.

## Environment

* OS: Windows 10 Pro 22H2 v19045.3803 (**Clean Installation**)
* CPU: Intel Xeon CPU E5-2450 @ 2.10GHz
* Memory: Samsung 1x8GB DDR3 1600 MHz
* Hard Drive: WDC 1TB 7.2K RPM SATA 6Gbps 3.5'' HDD

## Screencast

https://github.com/Watfaq/clash-rs/assets/34526560/6fecf2a2-1efd-496c-9405-39a380e0f9ff

**Comment by ibigbug** [comment]
Might be https://github.com/Watfaq/clash-rs/issues/127

Can you try using different DNS and see if it improves ?

**Comment by ericclose** [comment]
> Might be #127
> 
> Can you try using different DNS and see if it improves ?

It doesn't make it better. :think

**Comment by ericclose** [comment]
I can confirm that version 0.1.14 has solved the issue of slow responsiveness.
