### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by OnePiece110** [Watfaq/clash-rs#293]
怎么打出ios的包

**Comment by OnePiece110** [comment]
ios 配置模版麻烦来一个可以吗

**Comment by OnePiece110** [comment]
感谢大佬的代码,我已经成功运行并打包出代码了,如果能支持json就更好了

**Comment by a365344743s** [comment]
> ios 配置模版麻烦来一个可以吗

请问ios搞定了吗

**Comment by Xixi0218** [comment]
搞定了

**Comment by a365344743s** [comment]
> 搞定了

能发我一份吗

**Comment by Xixi0218** [comment]
> > 搞定了
> 
> 
> 
> 能发我一份吗

有很多问题，网络不稳定，而且切换网络就会连不上网了

**Comment by a365344743s** [comment]
> > > 搞定了
> > 
> > 
> > 能发我一份吗
> 
> 有很多问题，网络不稳定，而且切换网络就会连不上网了

这样啊，试过leaf吗，好像没有这些问题

**Comment by Xixi0218** [comment]
> > > > 搞定了
> 
> > > 
> 
> > > 
> 
> > > 能发我一份吗
> 
> > 
> 
> > 有很多问题，网络不稳定，而且切换网络就会连不上网了
> 
> 
> 
> 这样啊，试过leaf吗，好像没有这些问题


leaf确实没有这些问题，所以我也很郁闷咋解决，clash-rs更完善

**Comment by a365344743s** [comment]
我看leaf ios 的lib有100多M，但是appstore上的leafvpn怎么才16M啊

**Comment by Xixi0218** [comment]
打包方式不对，换个姿势

**Comment by a365344743s** [comment]
> 打包方式不对，换个姿势
我用的这个，不是标准方式吗
cargo build -p leaf-ffi --target aarch64-apple-ios --release

**Comment by Xixi0218** [comment]
你研究下，反正leaf还不支持vmess aead也是难搞的，问题都挺多的

**Comment by a365344743s** [comment]
> 你研究下，反正leaf还不支持vmess aead也是难搞的，问题都挺多的

我测试是支持的啊

**Comment by Xixi0218** [comment]
你改造过了吧，源码根本不支持呀

**Comment by a365344743s** [comment]
我看它代码像是有的啊
![image](https://github.com/user-attachments/assets/8834d08d-7c86-4e51-a2bc-c79487596af8)

**Comment by Xixi0218** [comment]
这个真不是，您仔细研究下吧
