### ISSUE TITLE
Http2Config's host field not match the opt in Http2Option

### ISSUE THREAD

**Issue by VendettaReborn** [Watfaq/clash-rs#322]
this is likely to be a bug in vmess implementation with http2 as the transport

i've tested the config combination of `vmess + h2`, but encounter the broken pipe error, and after i debug the network traffic with wireshark, i found that the v2ray server return a `404 not found`.

![2024-03-15_23-53](https://github.com/Watfaq/clash-rs/assets/149785583/6e747319-c815-4f39-a2f5-0f17a27eb3ea)

After digging into the v2ray's source code, i found that v2ray [`calls isValidHost`](https://github.com/v2fly/v2ray-core/blob/v5.14.0/transport/internet/http/hub.go#L57) after receiving the request, what the [`isValidHost`](https://github.com/v2fly/v2ray-core/blob/master/transport/internet/http/config.go#L18) does is simple as well: 

It just compare the host in the request header with the hosts in server's config. If no item is matched, the vmess server's transport layer will return 404. 

```go
func (c *Config) getHosts() []string {
	if len(c.Host) == 0 {
		return []string{"www.example.com"}
	}
	return c.Host
}

func (c *Config) isValidHost(host string) bool {
	hosts := c.getHosts()
	for _, h := range hosts {
		if h == host {
			return true
		}
	}
	return false
}
```

Back to our rust code, it seems that the `h2_builder` use the wrong hosts

```rust
let h2_builder = Http2Config {
    hosts: vec![self.opts.server.clone()],
    method: http::Method::GET,
    headers: HashMap::new(),
    path: opt.path.to_owned().try_into().expect("invalid H2 path"),
};
```

the fix is also simple: change the `vec![self.opts.server.clone()]` into `opt.host.clone()`

**Comment by VendettaReborn** [comment]
Btw, interestingly, there is any possibility of returning 404: the configured path in server's http2 settings is not the **prefix** of client's http2 request path.

in another words, if the server's `streamSettings. httpSettings. path = "/test"`, the client's request path is `"/testhahaha"`, it  will succeed as well, the same with the request path of `"test"`

**Comment by VendettaReborn** [comment]
And I think if we apply the integration test with docker (simple ping pong test, or proxy of example.org), similar mistakes can be found as early as possible

**Comment by ibigbug** [comment]
thanks! yeah i think you are right, we should add more tests for this
