### ISSUE TITLE
怎么进行链式代理

### ISSUE THREAD

**Issue by a365344743s** [Watfaq/clash-rs#434]
在META中我们可以使用 [dialer-proxy](https://wiki.metacubex.one/config/proxies/dialer-proxy/#dialer-proxy)[¶](https://wiki.metacubex.one/config/proxies/dialer-proxy/#dialer-proxy)
在calsh-rs需要怎么配置呢

**Comment by ibigbug** [comment]
it's not supported.

使用 relay 不能满足需求么

**Comment by a365344743s** [comment]
relay 有一些使用限制，Meta 说relay以后会[废弃](https://github.com/MetaCubeX/mihomo/issues/1035#issuecomment-1976466582)掉。我们也尝试过使用tunnel，但是tunnel配置有点麻烦。

**Comment by ibigbug** [comment]
try the latest release: https://github.com/Watfaq/clash-rs/releases/tag/latest

https://github.com/Watfaq/clash-rs/blob/master/clash/tests/data/config/ss.yaml#L53
