### ISSUE TITLE
Wireguard implementation is extremely slow

### ISSUE THREAD

**Issue by fgsfds** [Watfaq/clash-rs#548]
This is youtube stats when using clash's own wireproxy implementation.

![image](https://github.com/user-attachments/assets/4997e3c4-dc5e-4cb1-9bf5-79231dc8b5df)

This is the same config, but using wireproxy + socks5 instead.

![image](https://github.com/user-attachments/assets/d9119eae-129b-452f-9f18-7eb4bbc7d8db)

**Comment by VendettaReborn** [comment]
we use boringtun as the dependency, but it may exist some problems now, see https://github.com/cloudflare/boringtun/issues/102
