### ISSUE TITLE
跑不起来呢

### ISSUE THREAD

**Issue by ArcCal** [Watfaq/clash-rs#568]
Mac os下，尝试运行，总是出现这种错误
clash-aarch64-apple-darwin、clash-aarch64-apple-darwin-static-crt都一样

/tmp/clash-rs -d /tmp        
dyld[44527]: Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
  Referenced from: <46163983-8D39-35B1-9DB1-6722C387F1E0> /tmp/clash-rs
  Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file)

请教，这是什么原因

**Comment by ibigbug** [comment]
can you try the build here https://github.com/Watfaq/clash-rs/actions/runs/10701661655?pr=573

**Comment by ArcCal** [comment]
It works.
