### ISSUE TITLE
[feature] nightly alpha build add version info

### ISSUE THREAD

**Issue by greenhat616** [Watfaq/clash-rs#596]
* use alpha version, such as `0.3.2-alpha.hash` to build
* add a `version.txt` file to let updater could check the updates
  * if use `update-tag` action, the hash of release in the page is updated, but the result of Github api is not.
  * the api of github have a request limit, and the file is not.

Maybe i can draft a pr to solve it later

**Comment by Itsusinn** [comment]
For nightly release，I would prefer add a `version.txt` alongs with binaries.
The content of `version.txt` might be:
- Hash of commit
- Time-stamp.
