### ISSUE TITLE
能否编译一个支持Android版本，现在安卓用的人那么多

### ISSUE THREAD

**Issue by yujack008** [Watfaq/clash-rs#639]
我试了clash-aarch64-unknown-linux-gnu和clash-aarch64-unknown-linux-musl都无法在安卓上面运行。
非常感谢！

或者能否指导一下怎么编译android版本，我也是刚学rust几个月，哈哈

**Comment by Itsusinn** [comment]
你是如何运行的？
使用termux

**Comment by Itsusinn** [comment]
![Screenshot_2024-11-05-19-47-08-870_com termux-edit](https://github.com/user-attachments/assets/2b01169c-3da1-4beb-98f1-7c89517aac3a)

**Comment by yujack008** [comment]
> 你是如何运行的？ 使用termux？

不是，我是直接adb push到/data/local/tmp/目录，然后直接运行命令行：
```
flame:/data/local/tmp # ls -al config.yaml
-rw-rw-rw- 1 root root 10 2024-11-05 14:43 config.yaml
flame:/data/local/tmp # ./clash-aarch64-unknown-linux-gnu
/system/bin/sh: ./clash-aarch64-unknown-linux-gnu: No such file or directory
1|flame:/data/local/tmp # ./clash-aarch64-unknown-linux-musl
start error: dns error: proto error: io error: No such file or directory (os error 2)
1|flame:/data/local/tmp # ls -al config.yaml
-rw-rw-rw- 1 root root 10 2024-11-05 14:43 config.yaml
flame:/data/local/tmp #
```
你是在termux上面运行可以吗？

**Comment by yujack008** [comment]
> 你是如何运行的？ 使用termux？

我这边测试了一下，如果是-v和-h参数是可以运行的：
flame:/data/local/tmp # ./clash-aarch64-unknown-linux-musl -v
clash-rs 0.7.0-alpha+sha.e2a4be4
flame:/data/local/tmp # ./clash-aarch64-unknown-linux-musl -h
Usage: clash-aarch64-unknown-linux-musl [OPTIONS]

Options:
  -d, --directory <DIRECTORY>
  -c, --config <FILE>          Specify configuration file [default: config.yaml] [short aliases: f]
  -t, --test-config            Test configuration and exit
  -v, --version                Print clash-rs version and exit [short aliases: V]
  -l, --log-file <LOG_FILE>    Additinally log to file
  -h, --help                   Print help
如果直接使用配置运行是无法运行的
flame:/data/local/tmp # ./clash-aarch64-unknown-linux-musl
start error: dns error: proto error: io error: No such file or directory (os error 2)
刚测试了一下，使用termux也是一样的问题。

我这边在Cross.toml里面添加：
[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:main"
然后使用cross编译了一个android版本，测试可以使用config.yaml运行
flame:/data/local/tmp # ./clash-rs
2024-11-06T00:53:53.620022Z  INFO ThreadId(01) clash_lib/src/common/mmdb.rs:37: downloading mmdb from https://github.com/Loyalsoldier/geoip/releases/download/202307271745/Country.mmdb
^C

**Comment by Itsusinn** [comment]
@ibigbug 有dns问题

**Comment by Itsusinn** [comment]
看来是libc导致了某种dns问题，正常来说android也能用musl.
@ibigbug 不知能不能解决，要是不行我加个android的target

**Comment by yujack008** [comment]
> 看来是libc导致了某种dns问题，正常来说android也能用musl. @ibigbug 不知能不能解决，要是不行我加个android的target

是的，我之前程序在android上运行也是用musl版本

**Comment by ibigbug** [comment]
> 看来是libc导致了某种dns问题，正常来说android也能用musl.
> @ibigbug 不知能不能解决，要是不行我加个android的target

先加个target吧。后面研究下这个什么问题

**Comment by Itsusinn** [comment]
Android的target已添加
