### ISSUE TITLE
Alpha Windows variant version numbers do not contain hashes

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Watfaq/clash-rs#642]
Judging from the picture in #639, the version number output of the Linux variant contains the `alpha` and hash fields.

However, for Windows variants, the version number output by using `-v` is `clash-rs 0.7.0`, regardless of whether it is an Alpha build or not.

This caused Windows users to be unable to correctly identify whether the build they were using was an Alpha build. This also affected downstream *Clash Nyanpasu* — after updating *Clash Rust Alpha* in the software, since its version number was still `0.7.0`, it would still prompt that a new update was available even after updating to the latest version.

**Comment by ibigbug** [comment]
https://github.com/actions/runner/issues/1636#issuecomment-1024531638

seems windows env vars are set in a slightly different way
