### ISSUE TITLE
riscv64 build possible?

### ISSUE THREAD

**Issue by AutisticShark** [Watfaq/clash-rs#655]
Has anyone successfully compiled clash-rs on the riscv64 arch yet? I am not familiar with Rust lang, could it be as simple as adding a compile option to the GitHub action, or require a code change?

I knew there are a lot of Golang solutions out there that can be easily cross-compiled for riscv64, but they are 1. massive binary size and 2. quite slow on current riscv64 hardware since nothing is accelerated and everything needs to be done in software.

Thanks.

**Comment by ibigbug** [comment]
You can try it out and get some ideas from here https://github.com/Watfaq/clash-rs/blob/master/.github/workflows/ci.yml

Usually it doesn't require code change however might need extra build environment setup

**Comment by AutisticShark** [comment]
I experimented with it on my fork, it looks like it failed because of the `ring` package

```
error: failed to run custom build command for `ring v0.16.20`
Caused by:
  process didn't exit successfully: `/target/debug/build/ring-3775fb799412049a/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:358:10:
  called `Option::unwrap()` on a `None` value
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Error: The process '/home/runner/.cargo/bin/cross' failed with exit code 101
```

It looks like the dependency needs to be updated to at least 0.17 to work on every target based on this [issue](https://github.com/briansmith/ring/issues/1765).

**Comment by ibigbug** [comment]
you can try to disable "onion" feature https://github.com/Watfaq/clash-rs/blob/master/.github/workflows/ci.yml#L126

0.16 is only required for tor clients
