### ISSUE TITLE
macOS SDK 14+ is required

### ISSUE THREAD

**Issue by aaronjheng** [Watfaq/clash-rs#657]
I'm trying to build clash-rs with nix (https://github.com/NixOS/nixpkgs/pull/360126).
It seems that clash-rs can only be built correctly when using macOS SDK 14 or higher. The main reason is that clash-rs has a dependency on tracing-oslog, which has some C bindings that affect compilation on lower macOs SDK versions. 
I'm not 100% sure, because these are areas I'm not very familiar with.
If it can be confirmed that this is indeed the case, I think the relevant build documentation should be updated to provide a detailed explanation of the compilation requirements on macOS.

**Comment by ibigbug** [comment]
could you try https://github.com/Watfaq/clash-rs/pull/658 ?

**Comment by aaronjheng** [comment]
Awesome, it works like a charm!
